name: Trying Self hosted runner trial 2
on:
  workflow_dispatch

jobs:
  build:

    runs-on: [self-hosted, windows, x64]

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - shell: cmd
      run: npm ci
    - shell: cmd
      run: npm run build --if-present
       
    - uses: actions/upload-artifact@v3.1.2
      with:
       name: Connectors-3.5.0
       path: public/
       
  test:
 
   needs: build
   runs-on: [self-hosted, windows, x64]
        
   steps: 
    - shell: cmd
      run: mkdir Artifactsv3.5.0
    - uses: actions/download-artifact@v3.0.2
      with:
       name: Connectors-3.5.0
       path: Artifactsv3.5.0
